stack: cflinuxfs2
buildpack: "https://github.com/cloudfoundry/ruby-buildpack.git#v1.7.3"
services:
- enviosya-arq-GF-redis
- apicostos-arq-GF-db
applications:
- name: apicostos-arq-GF-app
  instances: 1
  memory: 512M
  disk_quota: 512M
  routes:
  - route: apicostos-arq-GF-app.mybluemix.net
  command: rails server -p $PORT
  services:
  - availability-monitoring-auto
- name: apicostos-arq-GF-sidekiq
  memory: 256M
  disk_quota: 256M
  instances: 1
  command: sidekiq
  health-check-type: process